/**
 * Auto-generated room metadata for map walkthrough tests.
 * Cross-referenced from server/src/data/maps.json + npcs.json.
 */
export interface RoomMeta {
  id: string; name: string;
  npcNames: string[];
  exitLetters: string[];
  pathFromTown: string[];
}

export const ALL_ROOMS: RoomMeta[] = [
  {id:"duan/hall", name:"段氏·天龙寺", npcNames:["段氏皇族弟子","一灯大师","段氏皇族弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","s"]},
  {id:"emei/foot", name:"峨眉·山门", npcNames:[], exitLetters:["n","s"], pathFromTown:["n","n","n","e","n"]},
  {id:"emei/golden", name:"峨眉·金顶", npcNames:["峨眉派弟子","灭绝师太","峨眉派弟子"], exitLetters:["s"], pathFromTown:["n","n","n","e","n","n"]},
  {id:"gaibang/forest1", name:"丐帮·杏子林入口", npcNames:[], exitLetters:["e","s","w"], pathFromTown:["n","n","n","w"]},
  {id:"gaibang/forest2", name:"丐帮·杏子林深处", npcNames:[], exitLetters:["n"], pathFromTown:["n","n","n","w","s"]},
  {id:"gaibang/hq", name:"丐帮·总舵", npcNames:["丐帮弟子","洪七公","丐帮弟子"], exitLetters:["w"], pathFromTown:["n","n","n","w","e"]},
  {id:"gumu/chamber", name:"古墓·密室", npcNames:["古墓派弟子","杨过","古墓派弟子"], exitLetters:["s"], pathFromTown:["n","n","n","n","n","n"]},
  {id:"gumu/entrance", name:"古墓·入口", npcNames:[], exitLetters:["n","s"], pathFromTown:["n","n","n","n","n"]},
  {id:"hell/hall", name:"修罗地狱·血池", npcNames:["修罗地狱弟子","修罗地狱掌门","修罗地狱弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","u","u","u","ne"]},
  {id:"henshan/hall", name:"衡山·回雁楼", npcNames:["衡山派弟子","莫大","衡山派弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","e"]},
  {id:"honghua/hall", name:"红花会·聚义厅", npcNames:["红花会弟子","陈家洛","红花会弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","w"]},
  {id:"hu/hall", name:"胡家·演武场", npcNames:["胡家弟子","华山派弟子","胡家掌门"], exitLetters:["n"], pathFromTown:["n","n","n","u","u","ne"]},
  {id:"huashan/foot", name:"华山·山脚", npcNames:[], exitLetters:["n","s"], pathFromTown:["n","n","n","n","e"]},
  {id:"huashan/path", name:"华山·山道", npcNames:[], exitLetters:["n","s"], pathFromTown:["n","n","n","n","e","n"]},
  {id:"huashan/peak", name:"华山·之巅", npcNames:["岳不群","华山派弟子"], exitLetters:["s"], pathFromTown:["n","n","n","n","e","n","n"]},
  {id:"jueqing/hall", name:"绝情谷·情花谷", npcNames:["绝情谷弟子","公孙止","绝情谷弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","u","nw"]},
  {id:"kunlun/hall", name:"昆仑·三清殿", npcNames:["昆仑派弟子","何足道","昆仑派弟子"], exitLetters:["e"], pathFromTown:["n","n","n","e","nw"]},
  {id:"lingjiu/hall", name:"灵鹫宫·缥缈峰", npcNames:["灵鹫宫弟子","虚竹子","灵鹫宫弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","e"]},
  {id:"lingxiao/hall", name:"凌霄城·雪峰殿", npcNames:["凌霄城弟子","史婆婆","凌霄城弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","se"]},
  {id:"meizhuang/hall", name:"梅庄·琴剑阁", npcNames:["梅庄弟子","黄钟公","梅庄弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","sw"]},
  {id:"miao/hall", name:"苗家·剑庐", npcNames:["苗家弟子","苗家掌门","苗家弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","u","u","n"]},
  {id:"mingjiao/hall", name:"明教·光明顶", npcNames:["明教弟子","张无忌","明教弟子"], exitLetters:["w"], pathFromTown:["n","n","n","n","ne"]},
  {id:"murong/hall", name:"慕容世家·燕子坞", npcNames:["慕容世家弟子","慕容复","慕容世家弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","n"]},
  {id:"ouyang/hall", name:"欧阳世家·白驼山", npcNames:["欧阳世家弟子","欧阳克","欧阳世家弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","u","u","s"]},
  {id:"quanzhen/hall", name:"全真教·重阳宫", npcNames:["全真教弟子","周伯通","全真教弟子"], exitLetters:["n"], pathFromTown:["n","n","n","n","sw"]},
  {id:"riyue/hall", name:"日月神教·黑木崖", npcNames:["日月神教弟子","任我行","日月神教弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","ne"]},
  {id:"shang/hall", name:"商家堡·八卦堂", npcNames:["商家堡弟子","商老太","商家堡弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","u","e"]},
  {id:"shaolin/gate", name:"少林寺·山门", npcNames:[], exitLetters:["s","w"], pathFromTown:["n","n","n","e","s"]},
  {id:"shaolin/hall", name:"少林寺·大雄宝殿", npcNames:["少林派弟子","达摩老祖","少林派弟子"], exitLetters:["e","n"], pathFromTown:["n","n","n","e","s","w"]},
  {id:"shaolin/training", name:"少林寺·练功房", npcNames:[], exitLetters:["s"], pathFromTown:["n","n","n","e","s","w","n"]},
  {id:"shenlong/hall", name:"神龙教·神龙岛", npcNames:["神龙教弟子","苏荃","神龙教弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","se"]},
  {id:"songshan/hall", name:"嵩山·封禅台", npcNames:["嵩山派弟子","左冷禅","嵩山派弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","u","w"]},
  {id:"tangmen/hall", name:"唐门·唐家堡", npcNames:["唐门弟子","唐门掌门","唐门弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","se"]},
  {id:"taohua/hall", name:"桃花岛·试剑亭", npcNames:["桃花岛弟子","黄药师","桃花岛弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","nw"]},
  {id:"tianlongsi/hall", name:"天龙寺·枯荣堂", npcNames:["天龙寺弟子","天龙寺掌门","天龙寺弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","u","u","nw"]},
  {id:"tiezhang/hall", name:"铁掌帮·铁掌峰", npcNames:["铁掌帮弟子","裘千仞","铁掌帮弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","sw"]},
  {id:"town/inn", name:"无名小镇·客栈", npcNames:["东厂官兵","小男孩","不知名草药","程老板","蓄精丹","九皇补心丹","小云丹","玉泉丹","雪参丹","血麒丹","龙涎丹","万寿丹","王掌柜"], exitLetters:["u","w"], pathFromTown:["e"]},
  {id:"town/inn_upstairs", name:"无名小镇·客栈二楼", npcNames:["神秘商人"], exitLetters:["d"], pathFromTown:["e","u"]},
  {id:"town/mainstreet", name:"无名小镇·主街", npcNames:["北京官兵","男孩","菜贩子","茶客","养精丹","引心丹","回阳无极丹","锁泉丹","小金丹","火麒丹","张德贵","龙王丹","药铺老板"], exitLetters:["n","s"], pathFromTown:["n"]},
  {id:"town/square", name:"无名小镇·广场", npcNames:["鳌拜","西厂官兵","男子","茶博士","陈老头","补精丹","还魂丹","大云丹","修罗","归元丹","罗刹","龟苓丹","说书人"], exitLetters:["e","n","s"], pathFromTown:[]},
  {id:"town/training", name:"无名小镇·练武场", npcNames:["武师"], exitLetters:["n"], pathFromTown:["s"]},
  {id:"ultra/hall", name:"绝世·武境", npcNames:["绝世高手弟子","绝世高手掌门","绝世高手弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","u","u","nw"]},
  {id:"wilderness/cave", name:"山林·洞穴", npcNames:["黑熊","十全大还丹","康府家丁","黑风寨主","玄武","chinese","张三","郭靖"], exitLetters:["e","sw"], pathFromTown:["n","n","n","n","w"]},
  {id:"wilderness/cliff", name:"山林·断崖", npcNames:["大补丹","鳌府家丁","小贩","青衣","软金束带","折扇","砍竹人","张三"], exitLetters:["e","n","nw","s","w"], pathFromTown:["n","n","n","e"]},
  {id:"wilderness/forest1", name:"山林·入口", npcNames:["山贼"], exitLetters:["e","n","s","u","w"], pathFromTown:["n","n","n"]},
  {id:"wilderness/forest2", name:"山林·深处", npcNames:["大还丹","混混","店小二","慕容豪","老船夫","王方平","袁紫衣","野狼","木岛主"], exitLetters:["e","n","ne","s","sw","w"], pathFromTown:["n","n","n","n"]},
  {id:"wilderness/gate", name:"山门", npcNames:["小还丹","卖花少女","店小二","知客和尚","老船夫","秦广王","封万里","龙岛主"], exitLetters:["n","s"], pathFromTown:["n","n"]},
  {id:"wilderness/hub1", name:"荒野·门派岔路1", npcNames:[], exitLetters:["d","e","n","ne","nw","s","se","sw","u","w"], pathFromTown:["n","n","n","u"]},
  {id:"wilderness/hub2", name:"荒野·门派岔路2", npcNames:[], exitLetters:["d","e","n","ne","nw","s","se","sw","u","w"], pathFromTown:["n","n","n","u","u"]},
  {id:"wilderness/hub3", name:"荒野·门派岔路3", npcNames:[], exitLetters:["d","e","n","ne","nw","s","se","sw","u","w"], pathFromTown:["n","n","n","u","u","u"]},
  {id:"wilderness/hub4", name:"荒野·门派岔路4", npcNames:[], exitLetters:["d","e","n","ne","s","w"], pathFromTown:["n","n","n","u","u","u","u"]},
  {id:"wudang/gate", name:"武当山·山门", npcNames:[], exitLetters:["e","w"], pathFromTown:["n","n","n","e","e"]},
  {id:"wudang/hall", name:"武当山·紫霄宫", npcNames:["武当派弟子","张三丰","武当派弟子"], exitLetters:["e","n"], pathFromTown:["n","n","n","e","e","w"]},
  {id:"wudang/training", name:"武当山·练武场", npcNames:[], exitLetters:["s"], pathFromTown:["n","n","n","e","e","w","n"]},
  {id:"wudu/hall", name:"五毒教·万蛊殿", npcNames:["五毒教弟子","何铁手","五毒教弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","u","se"]},
  {id:"xiakedao/hall", name:"侠客岛·石室", npcNames:["侠客岛弟子","侠客岛弟子","侠客岛弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","u","sw"]},
  {id:"xiaoyao/hall", name:"逍遥派·琅嬛阁", npcNames:["逍遥派弟子","无崖子","逍遥派弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","n"]},
  {id:"xingxiu/hall", name:"星宿派·星宿海", npcNames:["星宿派弟子","摘星子","星宿派弟子"], exitLetters:["e"], pathFromTown:["n","n","n","n","w","sw"]},
  {id:"xuanming/hall", name:"玄冥谷·冰窟", npcNames:["玄冥谷弟子","鹤笔翁","玄冥谷弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","u","u","u","n"]},
  {id:"xuedao/hall", name:"血刀门·血池", npcNames:["血刀门弟子","血刀老祖","血刀门弟子"], exitLetters:["s"], pathFromTown:["n","n","n","u","u","u","u","s"]},
  {id:"xueshan/hall", name:"雪山派·凌霄阁", npcNames:["雪山派弟子","雪山派掌门","雪山派弟子"], exitLetters:["w"], pathFromTown:["n","n","n","u","nw"]},
  {id:"yunlong/hall", name:"云龙门·飞云阁", npcNames:["云龙门弟子","玄贞道长","云龙门弟子"], exitLetters:["e"], pathFromTown:["n","n","n","u","u","u","u","e"]},
  {id:"zhenyuan/hall", name:"震远镖局·练武厅", npcNames:["震远镖局弟子","震远镖局掌门","震远镖局弟子"], exitLetters:["n"], pathFromTown:["n","n","n","u","u","u","u","w"]},
];